import logger from '../utils/logger.js';

const DEFAULT_EXPERT_ANSWER_SECONDS = 5;

/**
 * Server-side Expert Mode priority manager.
 *
 * Every room has an independent queue.
 *
 * Important:
 * - Client timestamps are never trusted.
 * - Duplicate raise-hand requests are rejected.
 * - Queue belongs to a specific question.
 * - Only the first participant has answer priority.
 */
class ExpertQueue {
  constructor() {
    this.rooms = new Map();
  }

  getRoomState(roomId) {
    if (!this.rooms.has(roomId)) {
      this.rooms.set(roomId, {
        questionId: null,
        queue: [],
      });
    }

    return this.rooms.get(roomId);
  }

  /**
   * Reset queue whenever a new question starts.
   */
  resetQueue(roomId, questionId = null) {
    this.rooms.set(roomId, {
      questionId: questionId ? String(questionId) : null,
      queue: [],
    });

    logger.info(
      `Expert queue reset: room=${roomId} question=${questionId || 'none'}`
    );
  }

  /**
   * Remove all state for a room.
   */
  deleteRoom(roomId) {
    this.rooms.delete(roomId);
  }

  /**
   * Raise hand.
   *
   * Timestamp is generated by the server.
   */
  raiseHand(roomId, questionId, participantId, participantName) {
    const state = this.getRoomState(roomId);

    if (!state.questionId) {
      return {
        success: false,
        reason: 'no_active_question',
      };
    }

    if (String(state.questionId) !== String(questionId)) {
      return {
        success: false,
        reason: 'question_not_active',
      };
    }

    const existingIndex = state.queue.findIndex(
      (entry) => String(entry.participantId) === String(participantId)
    );

    if (existingIndex !== -1) {
      return {
        success: false,
        reason: 'already_raised',
        position: existingIndex + 1,
        total: state.queue.length,
      };
    }

    const now = Date.now();

    const entry = {
      participantId: String(participantId),
      participantName,
      raisedAt: now,
      order: state.queue.length + 1,
    };

    state.queue.push(entry);

    logger.info(
      `Expert raise hand: room=${roomId} question=${questionId} participant=${participantId} position=${entry.order}`
    );

    return {
      success: true,
      position: entry.order,
      total: state.queue.length,
      raisedAt: now,
    };
  }

  /**
   * Get current queue.
   */
  getQueue(roomId) {
    return this.getRoomState(roomId).queue;
  }

  /**
   * Get current question attached to queue.
   */
  getQuestionId(roomId) {
    return this.getRoomState(roomId).questionId;
  }

  /**
   * First participant currently having priority.
   */
  getTopPriority(roomId) {
    const queue = this.getQueue(roomId);

    if (queue.length === 0) {
      return null;
    }

    return queue[0];
  }

  /**
   * Check whether participant currently owns answer priority.
   */
  isPriorityParticipant(roomId, participantId) {
    const top = this.getTopPriority(roomId);

    if (!top) {
      return false;
    }

    return String(top.participantId) === String(participantId);
  }

  /**
   * Determine whether the current priority participant has
   * waited longer than the configured answer window.
   */
  hasPriorityTimedOut(roomId, answerSeconds = DEFAULT_EXPERT_ANSWER_SECONDS) {
    const top = this.getTopPriority(roomId);

    if (!top) {
      return false;
    }

    return Date.now() >= top.raisedAt + answerSeconds * 1000;
  }

  /**
   * Remove a participant from the queue.
   */
  removeFromQueue(roomId, participantId) {
    const state = this.getRoomState(roomId);

    const index = state.queue.findIndex(
      (entry) => String(entry.participantId) === String(participantId)
    );

    if (index === -1) {
      return false;
    }

    state.queue.splice(index, 1);

    state.queue.forEach((entry, indexValue) => {
      entry.order = indexValue + 1;
    });

    return true;
  }

  /**
   * Remove the current priority participant.
   */
  removeTopPriority(roomId) {
    const state = this.getRoomState(roomId);

    if (state.queue.length === 0) {
      return null;
    }

    const removed = state.queue.shift();

    state.queue.forEach((entry, index) => {
      entry.order = index + 1;
    });

    return removed;
  }

  /**
   * Get safe queue data for clients.
   */
  getQueueState(roomId) {
    const state = this.getRoomState(roomId);

    return state.queue.map((entry) => ({
      participantId: entry.participantId,
      participantName: entry.participantName,
      order: entry.order,
      raisedAt: entry.raisedAt,
    }));
  }
}

const expertQueue = new ExpertQueue();

export default expertQueue;